[tool.poetry]
name = "twitch-alert-bot"
version = "0.1.0"
description = "Indicates on Twitter when a certain streamer is live on Twitch"
authors = ["P. R. d. O. <d.ol.rod@protonmail.com>"]
license = "GPLv3"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.27.1"
twitchAPI = "^2.5.1"
python-twitter = "^3.5"
PyYAML = "^6.0"

[tool.poetry.dev-dependencies]
pycodestyle = "^2.8.0"
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
