[tool.poetry]
name = "twitch-alert-bot"
version = "0.1.0"
description = "Indicates on Twitter when a Twitch streamer is live"
authors = ["P. R. d. O. <d.ol.rod@protonmail.com>"]
license = "GPLv3"
packages = [
	{ include = "tab" }
]

[tool.poetry.dependencies]
python = "^3.9"
requests = "2.26.0"
python-twitter = "3.5"
PyYAML = "5.4.1"
twitchAPI = "2.5.0"

[tool.poetry.dev-dependencies]
pycodestyle = "2.8.0"
pytest = "6.2.5"

[tool.poetry.scripts]
twitch_alert_bot = "tab.__main__:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
