credentials:
        twitch:
                client_id: "test"
                secret: "test"
        twitter:
                consumer_key: "test"
                consumer_secret: "test"
                access_key: "test"
                access_secret: "test"
# Interval to poll for results, in seconds. Default is 120
extras:
        twitter:
                # Although optional, this is useful for the duplicated tweet detection feature.
                user: "test"
                tweet_count: 10
polling_interval: 180
# Message to tweet. Can surpass the character limit, but this will
# mean the tweet will be divided into other tweets after surpassing the limit.
# Accepts the following keywords:
# {streamer_username}: Will use the original Twitch user name
# {custom_name}: Will use the provided name on the streamers entry.
#                If none is provided, will use twitch_username by default
# {game_name}: Will show the game being played
# {stream_url}: Will show Twitch channel url (twitch.tv/username)
# {twitter_handle}: Will use the Twitter handle.
#                   If none is provided, it will show as empty.
# {twitter_handle_with_at}: Will show the Twitter handle with the at sign at the beginning (e.g. @myhandle).
#                           If none is provided, it will show as empty.
# {twitter_handle_with_at_enclosed}: Similar to twitter_handle_with_at, but inside parentheses (e.g. (@myhandle)).
#                                    If none is provided, it will show as empty.
# {livestream_title}: Will show the livestream title
# When using {n} before or after one of the keywords, it will indicate how many
#   spaces you want before/after. If the keyword does not exist, then it won't
#   show anything
# e.g.: {3}{custom_name} will become "   My Custom Name"
#       {custom_name}{1} will become "My Custom Name "
#       {3}{custom_name}{2} will become "   My Custom Name  "
#       Test{1}{twitter_handle}! but there is no Twitter handle
#         becomes "Test!"
message:
  text: "{streamer_username} is live!"
streamers:
# You can provide the following info:
# Twitch User (required)
# Twitter Handle (optional)
# Name (optional)
# The format is (supposing "a_seagull" and "a_turtle" are Twitch users):
# 1) If there is a Twitter handle or a custom name
- "a_seagull":
  twitter_handle: "seagullstreamer"
  name: "Seagull Streamer"
# 2) Only the Twitch user
- "a_turtle"
